# Generated by Django 4.2.7 on 2023-12-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_phone',
        ),
    ]
