# Generated by Django 4.2.7 on 2023-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
