# Generated by Django 4.2.7 on 2023-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
