# Generated by Django 4.2.7 on 2023-12-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_phone',
        ),
    ]
