# Generated by Django 4.2.7 on 2023-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('in_process', 'In Process'), ('completed', 'Completed')], default='opened', max_length=20),
        ),
    ]
